version: "3"
services:
  
  django:
    image: frolvlad/alpine-python3
    volumes: 
      - ./django-realworld-example-app:/drf
    working_dir: /drf
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    ports: 
      - "8000:8000"
    networks: 
      - internal_net
  
  react:
    image: node:12.2.0-alpine
    volumes: 
      - ./react:/app
    working_dir: /app
    command: sh -c "npm i && npm start --host=0.0.0.0:4100"
    environment: 
      - NODE_ENV=development
    ports: 
      - "4100:4100"
    networks: 
      - internal_net

networks: 
  internal_net: